### ISSUE TITLE
Any plan to support the nerf-on-the-go dataset used in the wild-gaussian paper?

### ISSUE THREAD

**Issue by Sugar55888** [nerfbaselines/nerfbaselines#27]

**Comment by jkulhanek** [comment]
Hi, the dataset is supported. Just download it from wildgaussian repo and point `—data` to the extracted directory. Or are you having issues with that?

**Comment by Sugar55888** [comment]
@jkulhanek Hi, I use the command nerfbaselines train --method kplanes --data ./data/drone/ --backend conda. But it appears: error: No supported dataset found in path /code/nerfbaselines/data/drone
   bundler: Could not find cameras.out in /code/nerfbaseli
            nes/data/drone
   nerfstudio: 3D points are requested but not present in dataset /code/nerfbaselines/data/drone
   colmap: Missing 'sparse' folder in COLMAP dataset
It seems the nerf-on-the-go data can be recognized for the method. How can I solve it?

**Comment by jkulhanek** [comment]
Hi, the data you have does not contain the 3D points needed for KPlanes (and 3DGS methods). You need to provide them in order to train the method. Alternatively, you can train a method that does not require 3D points. You can try: instant-ngp, nerfacto, 3dgs-mcmc (with --set init_type=random). An option would also be to run e.g. COLMAP on the data to obtain the 3D points. Refer to the COLMAP docs to learn how to triangulate the points while using fixed poses.

**Comment by jkulhanek** [comment]
Also note, that the dataset used in WildGaussian is supported as the released data contain the 3D points. In your case the 3D points are missing. The drone scene wasn't released as part of WG, so I assume you downloaded it from somewhere else (e.g. the original Nerf on-the-go paper which did not release the 3D points).

**Comment by jkulhanek** [comment]
Note, that KPlanes needs the 3D points to estimate znear,zfar for cameras (look at the original codebase).

**Comment by Sugar55888** [comment]
@jkulhanek Thank you for your detailed answer！ I have successfully run kplanes！ By the way, I would like to ask if there is a way to install a specific version of the package when using conda backend in nerfbaseline. Because when I directly use the command nerfbaselines train --method wild-gaussians --data ./data/drone --backend conda to run wildgaussian, there will be a mismatch between the pytorch version and the cuda version.

**Comment by Sugar55888** [comment]
I have add a new issue about this problem.
