### ISSUE TITLE
gsplat parameters of Photo Tourism

### ISSUE THREAD

**Issue by hecodeit** [nerfbaselines/nerfbaselines#30]
What are the gsplat parameters set for the Photo Tourism dataset? Why gsplat can got multiple appearance?

**Comment by jkulhanek** [comment]
Here are the parameters: https://github.com/nerfbaselines/nerfbaselines/blob/1327fb17b59044cb7a1cdf108464b4e6da396880/nerfbaselines/methods/gsplat_spec.py#L75
