### ISSUE TITLE
ModuleNotFoundError: No module named 'nerfbaselines._version'

### ISSUE THREAD

**Issue by sheshap** [nerfbaselines/nerfbaselines#32]
Hi Team,

I downloaded nerfbaselines, pip installed nerfbaselines and started training for mip360 dataset (using python version).
I encountered the below error.

ModuleNotFoundError: No module named 'nerfbaselines._version'

**Comment by jkulhanek** [comment]
Hi, please post full commands you used to install nerfbaselines and command you used which caused the error.

**Comment by jkulhanek** [comment]
This should not happen anymore even if you simply copy the code without installing it. It will only give a warning and disable some features.
