### ISSUE TITLE
[feature request] How to export 3d mesh from training results?

### ISSUE THREAD

**Issue by zydmtaichi** [nerfbaselines/nerfbaselines#6]
nerfbaseline cmd tool is a nice work on intergrating some new 3d recons models. However, the tool only has the viewer option to take a look on 3d structure without option to export 3d. can we have some function in cmd line to export mesh assets?

**Comment by jkulhanek** [comment]
Thanks, I plan to add this feature soon(ish).

**Comment by jkulhanek** [comment]
Hi, I plan to slowly release this feature. Please let me know which methods you would like to have added first.

**Comment by zydmtaichi** [comment]
> Hi, I plan to slowly release this feature. Please let me know which methods you would like to have added first.

Hi, I hope we can add a `export` option in nerfbaseline command tool. Like the `render` option, it can be set the `--output` for location of output file, `--checkpoint` for the weight of model used and maybe `--file_type` for the format of output file( e.g ply,glb,obj...)

**Comment by jkulhanek** [comment]
There already is `export_mesh` method on the Method class, although no cli yet. The issue is that this has to be implemented for various methods. The question was which methods would you like to see added first.

**Comment by zydmtaichi** [comment]
> There already is `export_mesh` method on the Method class, although no cli yet. The issue is that this has to be implemented for various methods. The question was which methods would you like to see added first.
Hi,
I check the repo and find the `export-mesh` branch which contain the `export_mesh_command` func in cli/_export_mesh.py and one `export_mesh` method in methods/colmap.py. I wish you can prioritize the [2D Gaussian Splatting](https://nerfbaselines.github.io/m-2d-gaussian-splatting) and [Gaussian Splatting](https://nerfbaselines.github.io/m-gaussian-splatting) first, thanks a lot for your patience and generous help.

**Comment by jkulhanek** [comment]
Gaussian splatting doesn't implement mesh exporting. There are ways to do it, but it wouldn't be the official implementation. 2DGS implements it in their repo so it should be just a matter of adding the bindings.

**Comment by jkulhanek** [comment]
I will do it, but probably next week.

**Comment by zydmtaichi** [comment]
> I will do it, but probably next week.
Hi,
I also visit the nerfstudio community and take a look on their docs. It seems the nerfstudio already implements the [TSDF Fusion](https://docs.nerf.studio/quickstart/export_geometry.html#tsdf-fusion) for all models, you can add and bind this mesh export method too.

**Comment by jkulhanek** [comment]
In the meantime, you can use nerfstudio directly to obtain meshes for nerfstudio-based methods (nerfacto, ...). The checkpoints can be loaded in nerfstudio. You can use ‘nerfbaselines shell —method nerfacto’ which drops you into a shell with nerfstudio installed

**Comment by jkulhanek** [comment]
Hi, I've skipped the TSDF for all methods (rendering depth for now). I also haven't written the bindings for the nerfstudio ns-export yet. Currently COLMAP, 2DGS, and GOF will be supported. I will revisit the nerfacto (with Poisson meshing ) later, but in general, I will prioritize adding SDF methods which are more suitable for mesh export.

**Comment by jkulhanek** [comment]
Please open a new PR with concrete methods you want the mesh export to be added.

**Comment by jkulhanek** [comment]
Btw, there are also mesh demos now. E.g., checkout GOF on blender/drums: https://nerfbaselines.github.io/demos/mesh/?p=https%3A%2F%2Fhuggingface.co%2Fdatasets%2Fjkulhanek%2Fnerfbaselines-supplementary%2Fresolve%2Fmain%2Fgaussian-opacity-fields%2Fblender%2Fdrums_mesh%2Fparams.json
