### ISSUE TITLE
Running with a custom dataset, changes size in formatting

### ISSUE THREAD

**Issue by Mikey-E** [nerfbaselines/nerfbaselines#9]
I have a custom dataset that I have been formatting with convert.py from https://github.com/autonomousvision/gaussian-opacity-fields so it will run with gaussian-opacity-fields, gaussian-splatting, mip-splatting. However this changes the size of the images in the "images" folder to be smaller than what they originally were. Do you believe it is best to run with the original size of the images or the smaller sizes? Either will work.

**Comment by jkulhanek** [comment]
Hi, what are the sizes? For 3DGS I would recommend keeping the sizes at around 1000px. (w*h) close to 1M pixels. In nerfbaselines you only need to downscale the images, camera matrices will be rescaled automatically.

**Comment by sheshap** [comment]
Hi @jkulhanek, more details about the issue mentioned by @Mikey-E can be found [here](https://github.com/autonomousvision/gaussian-opacity-fields/issues/79)

Please review. Thanks

**Comment by jkulhanek** [comment]
From what I understand, the question is more about what convert.py in https://github.com/autonomousvision/gaussian-opacity-fields repo does? In that case the https://github.com/autonomousvision/gaussian-opacity-fields repo is a better place to ask the question.

**Comment by Mikey-E** [comment]
We were just concerned if having smaller sized images (after we use convert.py to format our own dataset) will be a problem for any of the nerfbaselines models, theoretically or otherwise, from a research perspective. If you are unsure that is understandable and okay, we just thought we'd reach out for any extra insight we can get.
